// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://johdlhuyhbqubzuliadk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvaGRsaHV5aGJxdWJ6dWxpYWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTI4MzAsImV4cCI6MjA2NDM2ODgzMH0.2XyQvnoDMJBQF8CfQsFBzrPZJKcFT8IsdfxmiPb7hzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);